def foo():
  # no errors
  return 1
